// File generated by the BNF Converter (bnfc 2.9.5).

package org.stella.typecheck;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.syntax.stella.Absyn.*;
import org.syntax.stella.PrettyPrinter;

/*** Visitor Design Pattern Skeleton. ***/

/* This implements the common visitor design pattern.
   Tests show it to be slightly less efficient than the
   instanceof method, but easier to use.
   Replace the R and A parameters with the desired return
   and context types.*/

  public class VisitTypeCheck
  {
  public static final String ERR_UNEXP_TYPE_PARAM = "ERROR_UNEXPECTED_TYPE_FOR_PARAMETER";
  public static final String ERR_UNEXP_TYPE_EXPR = "ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION";
  public static final String ERR_UNEXP_LAMBDA    = "ERROR_UNEXPECTED_LAMBDA";
  public static final String ERR_NOT_A_FUNCTION  = "ERROR_NOT_A_FUNCTION";
  public static final String ERR_UNDEF_VAR       = "ERROR_UNDEFINED_VARIABLE";
  public static final String ERR_MISSING_MAIN    = "ERROR_MISSING_MAIN";
  public static final String ERR_UNEXP_TUPLE     = "ERROR_UNEXPECTED_TUPLE";
  public static final String ERR_NOT_A_TUPLE     = "ERROR_NOT_A_TUPLE";

  public static final String ERR_AMBIGUOUS_SUM_TYPE         = "ERROR_AMBIGUOUS_SUM_TYPE";
  public static final String ERR_AMBIGUOUS_LIST_TYPE        = "ERROR_AMBIGUOUS_LIST_TYPE";
  public static final String ERR_ILLEGAL_EMPTY_MATCHING     = "ERROR_ILLEGAL_EMPTY_MATCHING";
  public static final String ERR_NONEXHAUSTIVE_MATCH        = "ERROR_NONEXHAUSTIVE_MATCH_PATTERNS";
  public static final String ERR_NOT_A_LIST                 = "ERROR_NOT_A_LIST";
  public static final String ERR_UNEXPECTED_LIST            = "ERROR_UNEXPECTED_LIST";
  public static final String ERR_UNEXPECTED_INJECTION       = "ERROR_UNEXPECTED_INJECTION";
  public static final String ERR_UNEXPECTED_PATTERN_FOR_TYPE= "ERROR_UNEXPECTED_PATTERN_FOR_TYPE";

  public static final String ERROR_NOT_A_REFERENCE          = "ERROR_NOT_A_REFERENCE";
  public static final String ERROR_EXCEPTION_TYPE_NOT_DECLARED = "ERROR_EXCEPTION_TYPE_NOT_DECLARED";
  public static final String ERROR_AMBIGUOUS_THROW_TYPE     = "ERROR_AMBIGUOUS_THROW_TYPE";
  public static final String ERROR_AMBIGUOUS_REFERENCE_TYPE = "ERROR_AMBIGUOUS_REFERENCE_TYPE";
  public static final String ERROR_AMBIGUOUS_PANIC_TYPE     = "ERROR_AMBIGUOUS_PANIC_TYPE";
  public static final String ERROR_UNEXPECTED_MEMORY_ADDRESS= "ERROR_UNEXPECTED_MEMORY_ADDRESS";
  public static final String ERROR_MISSING_RECORD_FIELDS    = "ERROR_MISSING_RECORD_FIELDS";
  public static final String ERROR_UNEXPECTED_RECORD_FIELDS = "ERROR_UNEXPECTED_RECORD_FIELDS";
  public static final String ERROR_UNEXPECTED_RECORD        = "ERROR_UNEXPECTED_RECORD";
  public static final String ERROR_NOT_A_RECORD             = "ERROR_NOT_A_RECORD";
  public static final String ERROR_UNEXPECTED_FIELD_ACCESS  = "ERROR_UNEXPECTED_FIELD_ACCESS";
  // Variants
  public static final String ERROR_AMBIGUOUS_VARIANT_TYPE   = "ERROR_AMBIGUOUS_VARIANT_TYPE";
  public static final String ERROR_UNEXPECTED_VARIANT       = "ERROR_UNEXPECTED_VARIANT";
  public static final String ERROR_UNEXPECTED_VARIANT_LABEL = "ERROR_UNEXPECTED_VARIANT_LABEL";

  public static class TypeError extends RuntimeException {
    public TypeError(String message) { super(message); }
  }

  public static class Context implements Cloneable {
    public final Map<String, Type> env = new HashMap<>();
    public Type expected = null;
    public Type exceptionType = null;

    public Context copy() {
      Context c = new Context();
      c.env.putAll(this.env);
      c.expected = this.expected;
      c.exceptionType = this.exceptionType;
      return c;
    }

    public Context withExpected(Type t) {
      Context c = copy();
      c.expected = t;
      return c;
    }

    public void bind(String name, Type t) {
      env.put(name, t);
    }

    public Type lookup(String name) {
      Type t = env.get(name);
      if (t == null) throw new TypeError(ERR_UNDEF_VAR + ": variable '" + name + "' is not defined");
      return t;
    }
  }

  static boolean typeEquals(Type a, Type b) {
    return a != null && b != null && a.equals(b);
  }

  static Type mkFun(Type param, Type ret) {
    ListType lt = new ListType();
    lt.add(param);
    return new TypeFun(lt, ret);
  }

  static Type expectBool(Type t, String where) {
    if (!(t instanceof TypeBool))
      throw new TypeError(ERR_UNEXP_TYPE_FOR(where, new TypeBool(), t));
    return t;
  }

  static String ERR_UNEXP_TYPE_FOR(String where, Type expected, Type found) {
    return ERR_UNEXP_TYPE_EXPR + ": expected " + PrettyPrinter.print(expected) +
           " in " + where + ", but found " + PrettyPrinter.print(found);
  }

  static void ensureEqual(String where, Type expected, Type found) {
    if (!typeEquals(expected, found)) {
      throw new TypeError(ERR_UNEXP_TYPE_FOR(where, expected, found));
    }
  }

  static TypeFun expectFunType(Type t, String where) {
    if (!(t instanceof TypeFun)) {
      throw new TypeError(ERR_NOT_A_FUNCTION + ": " + where + " has type " + PrettyPrinter.print(t));
    }
    return (TypeFun) t;
  }

  static TypeTuple expectTupleType(Type t, String where) {
    if (!(t instanceof TypeTuple)) {
      throw new TypeError(ERR_NOT_A_TUPLE + ": " + where + " has type " + PrettyPrinter.print(t));
    }
    return (TypeTuple) t;
  }

  static TypeList expectListType(Type t, String where) {
    if (!(t instanceof TypeList)) {
      throw new TypeError(ERR_NOT_A_LIST + ": " + where + " has type " + PrettyPrinter.print(t));
    }
    return (TypeList) t;
  }

  static TypeRef expectRefType(Type t, String where) {
    if (!(t instanceof TypeRef)) {
      throw new TypeError(ERROR_NOT_A_REFERENCE + ": " + where + " has type " + PrettyPrinter.print(t));
    }
    return (TypeRef) t;
  }

  public class ProgramVisitor<R,A> implements org.syntax.stella.Absyn.Program.Visitor<R,A>
  {
    private Type declaredExceptionType = null;
    public R visit(org.syntax.stella.Absyn.AProgram p, A arg)
    { /* Typecheck a complete program */
      Context ctx = (Context) arg;
      boolean hasMain = false;
      for (org.syntax.stella.Absyn.Decl x: p.listdecl_) {
        if (x instanceof DeclExceptionType det) {
          declaredExceptionType = det.type_;
        }
      }
      for (org.syntax.stella.Absyn.Decl x: p.listdecl_) {
        if (x instanceof DeclFun df) {
          if (df.listparamdecl_.size() != 1 || !(df.returntype_ instanceof SomeReturnType srt)) {
            continue;
          }
          AParamDecl param = (AParamDecl) df.listparamdecl_.get(0);
          Type paramTy = param.type_;
          Type retTy = srt.type_;
          Type fTy = mkFun(paramTy, retTy);
          ctx.bind(df.stellaident_, fTy);
          if ("main".equals(df.stellaident_)) hasMain = true;
        }
      }
      if (!hasMain) {
        throw new TypeError(ERR_MISSING_MAIN + ": program does not define a main function");
      }

      ctx.exceptionType = declaredExceptionType;
      for (org.syntax.stella.Absyn.Decl x: p.listdecl_) {
        x.accept(new DeclVisitor<R,A>(), arg);
      }
      return null;
    }
    Type getDeclaredExceptionType() { return declaredExceptionType; }
  }
  public class LanguageDeclVisitor<R,A> implements org.syntax.stella.Absyn.LanguageDecl.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.LanguageCore p, A arg)
    { /* Code for LanguageCore goes here */
      return null;
    }
  }
  public class ExtensionVisitor<R,A> implements org.syntax.stella.Absyn.Extension.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.AnExtension p, A arg)
    { /* Code for AnExtension goes here */
      for (String x: p.listextensionname_) {
        //x;
      }
      return null;
    }
  }
  public class DeclVisitor<R,A> implements org.syntax.stella.Absyn.Decl.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.DeclFun p, A arg)
    { /* Typecheck a function declaration */
      Context ctx = (Context) arg;
      if (!(p.returntype_ instanceof SomeReturnType srt)) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": function '" + p.stellaident_ + "' must have a return type");
      }
      if (p.listparamdecl_.size() != 1 || !(p.listparamdecl_.get(0) instanceof AParamDecl)) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": function '" + p.stellaident_ + "' must take exactly one parameter");
      }
      AParamDecl param = (AParamDecl) p.listparamdecl_.get(0);
      Type paramTy = param.type_;
      Type retTy = srt.type_;

      Context bodyCtx = ctx.copy();
      bodyCtx.bind(param.stellaident_, paramTy);

      bodyCtx.expected = retTy;
      Type bodyTy = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) bodyCtx);
      ensureEqual("function '" + p.stellaident_ + "' return", retTy, bodyTy);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.DeclFunGeneric p, A arg)
    { /* Code for DeclFunGeneric goes here */
      DeclFun df = new DeclFun(p.listannotation_, p.stellaident_, p.listparamdecl_, p.returntype_, p.throwtype_, p.listdecl_, p.expr_);
      return visit(df, arg);
    }
    public R visit(org.syntax.stella.Absyn.DeclTypeAlias p, A arg)
    { /* Code for DeclTypeAlias goes here */
      //p.stellaident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.DeclExceptionType p, A arg)
    { /* Code for DeclExceptionType goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.DeclExceptionVariant p, A arg)
    { /* Code for DeclExceptionVariant goes here */
      //p.stellaident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class LocalDeclVisitor<R,A> implements org.syntax.stella.Absyn.LocalDecl.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.ALocalDecl p, A arg)
    { /* Code for ALocalDecl goes here */
      p.decl_.accept(new DeclVisitor<R,A>(), arg);
      return null;
    }
  }
  public class AnnotationVisitor<R,A> implements org.syntax.stella.Absyn.Annotation.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.InlineAnnotation p, A arg)
    { /* Code for InlineAnnotation goes here */
      return null;
    }
  }
  public class ParamDeclVisitor<R,A> implements org.syntax.stella.Absyn.ParamDecl.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.AParamDecl p, A arg)
    { /* Code for AParamDecl goes here */
      //p.stellaident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ReturnTypeVisitor<R,A> implements org.syntax.stella.Absyn.ReturnType.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.NoReturnType p, A arg)
    { /* Code for NoReturnType goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.SomeReturnType p, A arg)
    { /* Code for SomeReturnType goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ThrowTypeVisitor<R,A> implements org.syntax.stella.Absyn.ThrowType.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.NoThrowType p, A arg)
    { /* Code for NoThrowType goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.SomeThrowType p, A arg)
    { /* Code for SomeThrowType goes here */
      for (org.syntax.stella.Absyn.Type x: p.listtype_) {
        x.accept(new TypeVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class TypeVisitor<R,A> implements org.syntax.stella.Absyn.Type.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.TypeAuto p, A arg)
    { /* Code for TypeAuto goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeFun p, A arg)
    { /* Code for TypeFun goes here */
      for (org.syntax.stella.Absyn.Type x: p.listtype_) {
        x.accept(new TypeVisitor<R,A>(), arg);
      }
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeForAll p, A arg)
    { /* Code for TypeForAll goes here */
      for (String x: p.liststellaident_) {
        //x;
      }
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeRec p, A arg)
    { /* Code for TypeRec goes here */
      //p.stellaident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeSum p, A arg)
    { /* Code for TypeSum goes here */
      p.type_1.accept(new TypeVisitor<R,A>(), arg);
      p.type_2.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeTuple p, A arg)
    { /* Code for TypeTuple goes here */
      for (org.syntax.stella.Absyn.Type x: p.listtype_) {
        x.accept(new TypeVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeRecord p, A arg)
    { /* Code for TypeRecord goes here */
      for (org.syntax.stella.Absyn.RecordFieldType x: p.listrecordfieldtype_) {
        x.accept(new RecordFieldTypeVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeVariant p, A arg)
    { /* Code for TypeVariant goes here */
      for (org.syntax.stella.Absyn.VariantFieldType x: p.listvariantfieldtype_) {
        x.accept(new VariantFieldTypeVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeList p, A arg)
    { /* Code for TypeList goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeBool p, A arg)
    { /* Code for TypeBool goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeNat p, A arg)
    { /* Code for TypeNat goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeUnit p, A arg)
    { /* Code for TypeUnit goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeTop p, A arg)
    { /* Code for TypeTop goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeBottom p, A arg)
    { /* Code for TypeBottom goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeRef p, A arg)
    { /* Code for TypeRef goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeVar p, A arg)
    { /* Code for TypeVar goes here */
      //p.stellaident_;
      return null;
    }
  }
  public class MatchCaseVisitor<R,A> implements org.syntax.stella.Absyn.MatchCase.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.AMatchCase p, A arg)
    { /* Code for AMatchCase goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
  }
  public class OptionalTypingVisitor<R,A> implements org.syntax.stella.Absyn.OptionalTyping.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.NoTyping p, A arg)
    { /* Code for NoTyping goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.SomeTyping p, A arg)
    { /* Code for SomeTyping goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class PatternDataVisitor<R,A> implements org.syntax.stella.Absyn.PatternData.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.NoPatternData p, A arg)
    { /* Code for NoPatternData goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.SomePatternData p, A arg)
    { /* Code for SomePatternData goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ExprDataVisitor<R,A> implements org.syntax.stella.Absyn.ExprData.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.NoExprData p, A arg)
    { /* Code for NoExprData goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.SomeExprData p, A arg)
    { /* Code for SomeExprData goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
  }
  public class PatternVisitor<R,A> implements org.syntax.stella.Absyn.Pattern.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.PatternCastAs p, A arg)
    { /* Code for PatternCastAs goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternAsc p, A arg)
    { /* Code for PatternAsc goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternVariant p, A arg)
    { /* Code for PatternVariant goes here */
      //p.stellaident_;
      Context ctx = (Context) arg;
      p.patterndata_.accept(new PatternDataVisitor<R,A>(), (A) ctx);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternInl p, A arg)
    { /* Code for PatternInl goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternInr p, A arg)
    { /* Code for PatternInr goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternTuple p, A arg)
    { /* Code for PatternTuple goes here */
      for (org.syntax.stella.Absyn.Pattern x: p.listpattern_) {
        x.accept(new PatternVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternRecord p, A arg)
    { /* Code for PatternRecord goes here */
      for (org.syntax.stella.Absyn.LabelledPattern x: p.listlabelledpattern_) {
        x.accept(new LabelledPatternVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternList p, A arg)
    { /* Code for PatternList goes here */
      for (org.syntax.stella.Absyn.Pattern x: p.listpattern_) {
        x.accept(new PatternVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternCons p, A arg)
    { /* Code for PatternCons goes here */
      p.pattern_1.accept(new PatternVisitor<R,A>(), arg);
      p.pattern_2.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternFalse p, A arg)
    { /* Code for PatternFalse goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternTrue p, A arg)
    { /* Code for PatternTrue goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternUnit p, A arg)
    { /* Code for PatternUnit goes here */
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternInt p, A arg)
    { /* Code for PatternInt goes here */
      //p.integer_;
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternSucc p, A arg)
    { /* Code for PatternSucc goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.PatternVar p, A arg)
    { /* Code for PatternVar goes here */
      //p.stellaident_;
      return null;
    }
  }
  public class LabelledPatternVisitor<R,A> implements org.syntax.stella.Absyn.LabelledPattern.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.ALabelledPattern p, A arg)
    { /* Code for ALabelledPattern goes here */
      //p.stellaident_;
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      return null;
    }
  }
  public class BindingVisitor<R,A> implements org.syntax.stella.Absyn.Binding.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.ABinding p, A arg)
    { /* Code for ABinding goes here */
      //p.stellaident_;
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ExprVisitor<R,A> implements org.syntax.stella.Absyn.Expr.Visitor<R,A>
  {
    private Map<String, Type> checkPatternAndBindings(Pattern pat, Type matched) {
      Map<String, Type> binds = new HashMap<>();
      if (pat instanceof PatternVar pv) {
        binds.put(pv.stellaident_, matched);
        return binds;
      }
      if (pat instanceof PatternInl pinl) {
        if (!(matched instanceof TypeSum ts)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": inl-pattern for non-sum type " + PrettyPrinter.print(matched));
        }
        binds.putAll(checkPatternAndBindings(pinl.pattern_, ts.type_1));
        return binds;
      }
      if (pat instanceof PatternInr pinr) {
        if (!(matched instanceof TypeSum ts)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": inr-pattern for non-sum type " + PrettyPrinter.print(matched));
        }
        binds.putAll(checkPatternAndBindings(pinr.pattern_, ts.type_2));
        return binds;
      }
      if (pat instanceof PatternList pl) {
        if (!(matched instanceof TypeList tl)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": list-pattern for non-list type " + PrettyPrinter.print(matched));
        }
        for (Pattern ptn : pl.listpattern_) {
          binds.putAll(checkPatternAndBindings(ptn, tl.type_));
        }
        return binds;
      }
      if (pat instanceof PatternCons pc) {
        if (!(matched instanceof TypeList tl)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": cons-pattern for non-list type " + PrettyPrinter.print(matched));
        }
        binds.putAll(checkPatternAndBindings(pc.pattern_1, tl.type_));
        binds.putAll(checkPatternAndBindings(pc.pattern_2, new TypeList(tl.type_)));
        return binds;
      }
      if (pat instanceof PatternTrue || pat instanceof PatternFalse) {
        if (!(matched instanceof TypeBool)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": boolean pattern for non-bool type " + PrettyPrinter.print(matched));
        }
        return binds;
      }
      if (pat instanceof PatternUnit) {
        if (!(matched instanceof TypeUnit)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": unit pattern for non-unit type " + PrettyPrinter.print(matched));
        }
        return binds;
      }
      if (pat instanceof PatternInt) {
        if (!(matched instanceof TypeNat)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": int pattern for non-nat type " + PrettyPrinter.print(matched));
        }
        return binds;
      }
      if (pat instanceof PatternTuple pt) {
        if (!(matched instanceof TypeTuple tt)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": tuple pattern for non-tuple type " + PrettyPrinter.print(matched));
        }
        if (pt.listpattern_.size() != tt.listtype_.size()) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE + ": tuple arity mismatch");
        }
        for (int i=0; i<pt.listpattern_.size(); i++) {
          binds.putAll(checkPatternAndBindings(pt.listpattern_.get(i), tt.listtype_.get(i)));
        }
        return binds;
      }
      if (pat instanceof PatternVariant pv) {
        if (!(matched instanceof TypeVariant tv)) {
          throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE +
                  ": variant1 pattern for non-variant type " + PrettyPrinter.print(matched));
        }

        boolean found = false;
        Type expectedPayloadType = null;

        for (VariantFieldType vft : tv.listvariantfieldtype_) {
          if (vft instanceof AVariantFieldType avt) {
            if (avt.stellaident_.equals(pv.stellaident_)) {
              found = true;
              if (avt.optionaltyping_ instanceof SomeTyping st) {
                expectedPayloadType = st.type_;
              }
              break;
            }
          }
        }

        if (!found) {
          throw new TypeError(ERROR_UNEXPECTED_VARIANT_LABEL +
                  ": label '" + pv.stellaident_ + "' not found in variant1 type");
        }

        if (pv.patterndata_ instanceof SomePatternData spd) {
          Pattern subPattern = spd.pattern_;

          if (expectedPayloadType == null) {
            throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE +
                    ": variant1 label '" + pv.stellaident_ + "' has no data, but pattern has");
          }

          binds.putAll(checkPatternAndBindings(subPattern, expectedPayloadType));
        } else {

          if (expectedPayloadType != null) {
            throw new TypeError(ERR_UNEXPECTED_PATTERN_FOR_TYPE +
                    ": variant1 label '" + pv.stellaident_ + "' expects data, but pattern has none");
          }
        }

        return binds;
      }
      return binds;
    }
    public R visit(org.syntax.stella.Absyn.Sequence p, A arg)
    { /* Sequencing: first must be Unit, result is type of second */
      Context ctx = (Context) arg;
      Type firstTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
      ensureEqual("sequencing first expression", new TypeUnit(), firstTy);
      return (R) p.expr_2.accept(new ExprVisitor<Type,A>(), arg);
    }
    public R visit(org.syntax.stella.Absyn.Let p, A arg)
    { /* Code for Let goes here */
      Context ctx = (Context) arg;
      Context inner = ctx.copy();
      for (org.syntax.stella.Absyn.PatternBinding x: p.listpatternbinding_) {
        if (!(x instanceof APatternBinding pb)) continue;

        if (!(pb.pattern_ instanceof PatternVar pv)) {
          throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": only variable patterns are supported in let-bindings");
        }
        Type rhsTy = (Type) pb.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
        //Type rhsTy = (Type) pb.expr_.accept(new ExprVisitor<>(), (A) ctx);
        inner.bind(pv.stellaident_, rhsTy);
      }
      return (R) p.expr_.accept(new ExprVisitor<Type,A>(), (A) inner);
    }
    public R visit(org.syntax.stella.Absyn.LetRec p, A arg)
    { /* Code for LetRec goes here */
      return visit(new Let(p.listpatternbinding_, p.expr_), arg);
    }
    public R visit(org.syntax.stella.Absyn.TypeAbstraction p, A arg)
    { /* Code for TypeAbstraction goes here */
      for (String x: p.liststellaident_) {
        //x;
      }
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Assign p, A arg)
    { /* Assignment: &T := T returns Unit */
      Context ctx = (Context) arg;
      Type lty = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), arg);
      TypeRef rt = expectRefType(lty, "assignment left");
      Type rty = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(rt.type_));
      ensureEqual("assignment right", rt.type_, rty);
      return (R) new TypeUnit();
    }
    public R visit(org.syntax.stella.Absyn.If p, A arg)
    { /* Code for If goes here */
      Context ctx = (Context) arg;
      Type condTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), arg);
      expectBool(condTy, "if condition");
      Type thenTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(ctx.expected));
      Type elseTy = (Type) p.expr_3.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(thenTy));
      ensureEqual("if branches", thenTy, elseTy);
      return (R) thenTy;
    }
    public R visit(org.syntax.stella.Absyn.LessThan p, A arg)
    { /* Code for LessThan goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.LessThanOrEqual p, A arg)
    { /* Code for LessThanOrEqual goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.GreaterThan p, A arg)
    { /* Code for GreaterThan goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.GreaterThanOrEqual p, A arg)
    { /* Code for GreaterThanOrEqual goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Equal p, A arg)
    { /* Code for Equal goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.NotEqual p, A arg)
    { /* Code for NotEqual goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.TypeAsc p, A arg)
    { /* Code for TypeAsc goes here */
      Context ctx = (Context) arg;
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(p.type_));
      ensureEqual("type ascription", p.type_, t);
      return (R) t;
    }
    public R visit(org.syntax.stella.Absyn.TypeCast p, A arg)
    { /* Code for TypeCast goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Abstraction p, A arg) {
      Context ctx = (Context) arg;

      if (p.listparamdecl_.size() != 1 || !(p.listparamdecl_.get(0) instanceof AParamDecl param)) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": anonymous functions must have exactly one parameter");
      }

      Type paramTy = param.type_;

      Type expectedFunType = ctx.expected;

      Context bodyCtx = ctx.copy();
      bodyCtx.bind(param.stellaident_, paramTy);

      if (expectedFunType instanceof TypeFun ef) {
        if (ef.listtype_.size() != 1) {
          throw new TypeError(ERR_UNEXP_LAMBDA + ": expected unary function type, got " +
                  PrettyPrinter.print(expectedFunType));
        }

        Type expectedParamTy = ef.listtype_.get(0);
        if (!typeEquals(expectedParamTy, paramTy)) {
          throw new TypeError(ERR_UNEXP_TYPE_PARAM +
                  ": expected parameter of type " + PrettyPrinter.print(expectedParamTy) +
                  ", but got " + PrettyPrinter.print(paramTy));
        }

        bodyCtx.expected = ef.type_;
        Type bodyTy = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) bodyCtx);
        ensureEqual("function body", ef.type_, bodyTy);

        return (R) expectedFunType;
      } else {
        //нет ожидаемого
        Type bodyTy = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) bodyCtx);
        Type lambdaTy = mkFun(paramTy, bodyTy);

        if (expectedFunType != null) {
          ensureEqual("lambda type", expectedFunType, lambdaTy);
          return (R) expectedFunType;
        }

        return (R) lambdaTy;
      }
    }
    public R visit(org.syntax.stella.Absyn.Variant p, A arg)
    { /* Variants (open sum with labels) */
      Context ctx = (Context) arg;
      if (ctx.expected != null && !(ctx.expected instanceof TypeVariant)) {
        throw new TypeError(ERROR_UNEXPECTED_VARIANT + ": expected " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeVariant) {
        TypeVariant tv = (TypeVariant) ctx.expected;

        boolean found = false;
        Type expectedPayload = null;

        for (VariantFieldType vft : tv.listvariantfieldtype_) {
          if (vft instanceof AVariantFieldType) {
            AVariantFieldType avt = (AVariantFieldType) vft;
            if (avt.stellaident_.equals(p.stellaident_)) {
              found = true;
              if (avt.optionaltyping_ instanceof SomeTyping) {
                expectedPayload = ((SomeTyping) avt.optionaltyping_).type_;
              }
              break;
            }
          }
        }
        if (!found) {
          throw new TypeError(ERROR_UNEXPECTED_VARIANT_LABEL + ": label '" + p.stellaident_ + "' not found");
        }
        if (p.exprdata_ instanceof SomeExprData) {
          Expr payload = ((SomeExprData) p.exprdata_).expr_;
          if (expectedPayload == null) {
            Type actual = (Type) payload.accept(new ExprVisitor<Type,A>(), arg);
            throw new TypeError(ERR_UNEXP_TYPE_FOR("variant payload", new TypeUnit(), actual));
          }
          Type actual = (Type) payload.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(expectedPayload));
          ensureEqual("variant payload", expectedPayload, actual);
        } else {
          if (expectedPayload != null) {
            throw new TypeError(ERR_UNEXP_TYPE_FOR("variant payload", expectedPayload, new TypeUnit()));
          }
        }
        return (R) tv;
      }
      throw new TypeError(ERROR_AMBIGUOUS_VARIANT_TYPE + ": cannot infer variant type for label '" + p.stellaident_ + "'");
    }
    public R visit(org.syntax.stella.Absyn.Match p, A arg) {
      Context ctx = (Context) arg;

      Type outerExpected = ctx.expected;

      Type scrutTy = (Type) p.expr_.accept(
              new ExprVisitor<Type,A>(),
              (A) ctx.withExpected(null)
      );

      if (p.listmatchcase_.isEmpty()) {
        throw new TypeError(ERR_ILLEGAL_EMPTY_MATCHING);
      }

      boolean needSumExhaust = scrutTy instanceof TypeSum;
      boolean needListExhaust = scrutTy instanceof TypeList;
      boolean needVariantExhaust = scrutTy instanceof TypeVariant;

      boolean hasInl = false, hasInr = false;
      boolean hasEmpty = false, hasCons = false;
      Set<String> coveredLabels = new HashSet<>();

      Type resultTy = null;

      //чекаем ветки
      for (org.syntax.stella.Absyn.MatchCase c : p.listmatchcase_) {
        AMatchCase mc = (AMatchCase) c;

        //чекаем переменные в паттерне
        Map<String, Type> binds = checkPatternAndBindings(mc.pattern_, scrutTy);

        if (mc.pattern_ instanceof PatternInl) hasInl = true;
        if (mc.pattern_ instanceof PatternInr) hasInr = true;
        if (mc.pattern_ instanceof PatternCons) hasCons = true;
        if (mc.pattern_ instanceof PatternList pl && pl.listpattern_.isEmpty()) hasEmpty = true;
        if (mc.pattern_ instanceof PatternVariant pv) {
          coveredLabels.add(pv.stellaident_);
        }

        Context branchCtx = ctx.copy();
        for (var e : binds.entrySet()) {
          branchCtx.bind(e.getKey(), e.getValue());
        }

        Type brTy;
        if (outerExpected != null) {
          brTy = (Type) mc.expr_.accept(
                  new ExprVisitor<Type,A>(),
                  (A) branchCtx.withExpected(outerExpected)
          );
          ensureEqual("match branch", outerExpected, brTy);
        } else {
          brTy = (Type) mc.expr_.accept(
                  new ExprVisitor<Type,A>(),
                  (A) branchCtx
          );
        }

        if (resultTy == null) {
          resultTy = brTy;
        } else {
          ensureEqual("match branches", resultTy, brTy);
        }
      }

      if (needSumExhaust && !(hasInl && hasInr)) {
        throw new TypeError(ERR_NONEXHAUSTIVE_MATCH +
                ": missing inl/inr branches");
      }
      if (needListExhaust && !(hasEmpty && hasCons)) {
        throw new TypeError(ERR_NONEXHAUSTIVE_MATCH + ": missing empty/cons branches");
      }
      if (needVariantExhaust) {
        TypeVariant tv = (TypeVariant) scrutTy;
        for (VariantFieldType vft : tv.listvariantfieldtype_) {
          AVariantFieldType avt = (AVariantFieldType) vft;
          if (!coveredLabels.contains(avt.stellaident_)) {
            throw new TypeError(ERR_NONEXHAUSTIVE_MATCH + ": missing branch for label '" + avt.stellaident_ + "'");
          }
        }
      }

      if (outerExpected != null) {
        return (R) outerExpected;
      }
      return (R) resultTy;
    }
    public R visit(org.syntax.stella.Absyn.List p, A arg)
    { /* List literal */
      Context ctx = (Context) arg;
      if (ctx.expected != null && !(ctx.expected instanceof TypeList)) {
        throw new TypeError(ERR_UNEXPECTED_LIST + ": expected1 " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeList el) {
        for (org.syntax.stella.Absyn.Expr x: p.listexpr_) {
          Type et = (Type) x.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(el.type_));
          ensureEqual("list element1", el.type_, et);
        }
        return (R) new TypeList(el.type_);
      }
      if (p.listexpr_.isEmpty()) {
        throw new TypeError(ERR_AMBIGUOUS_LIST_TYPE + ": cannot infer element type of []");
      }

      //без ожидаемого типа
      Type first = (Type) p.listexpr_.get(0).accept(new ExprVisitor<Type,A>(), arg);
      for (int i=1;i<p.listexpr_.size();i++) {
        Type et = (Type) p.listexpr_.get(i).accept(new ExprVisitor<Type,A>(), arg);
        ensureEqual("list element2", first, et);
      }
      return (R) new TypeList(first);
    }
    public R visit(org.syntax.stella.Absyn.Add p, A arg)
    { /* Code for Add goes here */
      throw new TypeError("Arithmetic operators are not supported in this subset");
    }
    public R visit(org.syntax.stella.Absyn.Subtract p, A arg)
    { /* Code for Subtract goes here */
      throw new TypeError("Arithmetic operators are not supported in this subset");
    }
    public R visit(org.syntax.stella.Absyn.LogicOr p, A arg)
    { /* Code for LogicOr goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Multiply p, A arg)
    { /* Code for Multiply goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Divide p, A arg)
    { /* Code for Divide goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.LogicAnd p, A arg)
    { /* Code for LogicAnd goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Ref p, A arg)
    { /* Ref/new: &T where T is type of expr */
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      return (R) new TypeRef(t);
    }
    public R visit(org.syntax.stella.Absyn.Deref p, A arg)
    { /* Deref: from &T to T */
      Context ctx = (Context) arg;
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
      TypeRef rt = expectRefType(t, "dereference");
      return (R) rt.type_;
    }
    public R visit(org.syntax.stella.Absyn.Application p, A arg) {
      Context ctx = (Context) arg;
      Type outerExpected = ctx.expected;

      //чекаем функцию
      Type calleeTy = (Type) p.expr_.accept(
              new ExprVisitor<Type,A>(),
              (A) ctx.withExpected(null)
      );

      Type resultTy = null;
      Type currentTy = calleeTy;

      for (org.syntax.stella.Absyn.Expr x : p.listexpr_) {
        TypeFun tf = expectFunType(currentTy, "application");
        if (tf.listtype_.size() != 1) {
          throw new TypeError(ERR_NOT_A_FUNCTION +
                  ": expected unary function, got " + PrettyPrinter.print(currentTy));
        }

        Type paramTy = tf.listtype_.get(0);

        //аргумент
        Type argTy = (Type) x.accept(
                new ExprVisitor<Type,A>(),
                (A) ctx.withExpected(paramTy)
        );

        ensureEqual("function argument", paramTy, argTy);
        currentTy = tf.type_;
        resultTy = currentTy;
      }

      if (resultTy == null) {
        resultTy = calleeTy;
      }

      if (outerExpected != null) {
        System.out.println("Application result: " + PrettyPrinter.print(resultTy));
        System.out.println("Outer expected: " + PrettyPrinter.print(outerExpected));
        ensureEqual("application result", outerExpected, resultTy);
        return (R) outerExpected;
      }

      return (R) resultTy;
    }
    public R visit(org.syntax.stella.Absyn.TypeApplication p, A arg)
    { /* Code for TypeApplication goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      for (org.syntax.stella.Absyn.Type x: p.listtype_) {
        x.accept(new TypeVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(org.syntax.stella.Absyn.DotRecord p, A arg)
    { /* Record field access */
      Context ctx = (Context) arg;
      System.out.println("DotRecord");
      Type t = (Type) p.expr_.accept(
              new ExprVisitor<Type,A>(),
              (A) ctx.withExpected(null)
      );
      if (!(t instanceof TypeRecord)) {
        throw new TypeError(ERROR_NOT_A_RECORD + ": field access on type " + PrettyPrinter.print(t));
      }
      TypeRecord tr = (TypeRecord) t;
      for (RecordFieldType rft : tr.listrecordfieldtype_) {
        if (rft instanceof ARecordFieldType) {
          ARecordFieldType arf = (ARecordFieldType) rft;
          if (arf.stellaident_.equals(p.stellaident_)) {
            Type fieldTy = arf.type_;

            if (ctx.expected != null) {
              ensureEqual("field access", ctx.expected, fieldTy);
            }
            return (R) arf.type_;
          }
        }
      }
      throw new TypeError(ERROR_UNEXPECTED_FIELD_ACCESS + ": field '" + p.stellaident_ + "' not present");
    }
    public R visit(org.syntax.stella.Absyn.DotTuple p, A arg) {
      Context ctx = (Context) arg;
      System.out.println("DotTuple");
      Type t = (Type) p.expr_.accept(
              new ExprVisitor<Type,A>(),
              (A) ctx.withExpected(null)
      );

      TypeTuple tt = expectTupleType(t, "tuple projection");

      if (p.integer_ < 1 || p.integer_ > tt.listtype_.size()) {
        throw new TypeError(ERR_NOT_A_TUPLE + ": tuple index out of bounds");
      }

      Type resultTy = tt.listtype_.get(p.integer_ - 1);

      if (ctx.expected != null) {
        ensureEqual("tuple projection", ctx.expected, resultTy);
        return (R) ctx.expected;
      }

      return (R) resultTy;
    }
    public R visit(org.syntax.stella.Absyn.Tuple p, A arg) {
      Context ctx = (Context) arg;

      // Сохраняем внешний ожидаемый тип для последующей проверки
      Type outerExpected = ctx.expected;

      // ВАЖНО: Кортеж проверяем БЕЗ ожидаемого типа!
      // Его тип выводится из элементов
      System.out.println("Tuple");
      ListType ts = new ListType();
      for (org.syntax.stella.Absyn.Expr x : p.listexpr_) {
        // Каждый элемент проверяем в исходном контексте, но без expected
        // (или можно с expected = null для каждого элемента)
        Type elemTy = (Type) x.accept(
                new ExprVisitor<Type,A>(),
                (A) ctx.withExpected(null)
        );
        ts.add(elemTy);
      }

      TypeTuple tupleTy = new TypeTuple(ts);

      // Если есть внешний ожидаемый тип, проверяем соответствие
      if (outerExpected != null) {
        ensureEqual("tuple", outerExpected, tupleTy);
        return (R) outerExpected;
      }

      return (R) tupleTy;
    }
    public R visit(org.syntax.stella.Absyn.Record p, A arg)
    { /* Record literal */
      Context ctx = (Context) arg;
      System.out.println("Record");
      if (ctx.expected != null && !(ctx.expected instanceof TypeRecord)) {
        throw new TypeError(ERROR_UNEXPECTED_RECORD + ": expected " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeRecord) {
        TypeRecord exp = (TypeRecord) ctx.expected;
        Map<String, Type> expMap = new HashMap<>();
        for (RecordFieldType rft : exp.listrecordfieldtype_) {
          ARecordFieldType arf = (ARecordFieldType) rft;
          expMap.put(arf.stellaident_, arf.type_);
        }
        Set<String> seen = new HashSet<>();
        for (Binding b : p.listbinding_) {
          ABinding ab = (ABinding) b;
          if (!expMap.containsKey(ab.stellaident_)) {
            throw new TypeError(ERROR_UNEXPECTED_RECORD_FIELDS + ": unexpected field '" + ab.stellaident_ + "'");
          }
        
          if (!seen.add(ab.stellaident_)) {
            throw new TypeError(ERROR_UNEXPECTED_RECORD_FIELDS + ": duplicate field '" + ab.stellaident_ + "'");
          }
          Type expectedFieldTy = expMap.get(ab.stellaident_);
          Type act = (Type) ab.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(expectedFieldTy));
          ensureEqual("record field '" + ab.stellaident_ + "'", expectedFieldTy, act);
        }
        if (seen.size() != expMap.size()) {
          throw new TypeError(ERROR_MISSING_RECORD_FIELDS + ": some fields are missing");
        }
        return (R) exp;
      }

      //нет ожидаемого
      ListRecordFieldType list = new ListRecordFieldType();
      for (Binding b : p.listbinding_) {
        ABinding ab = (ABinding) b;
        Type ty = (Type) ab.expr_.accept(new ExprVisitor<Type,A>(), arg);
        list.add(new ARecordFieldType(ab.stellaident_, ty));
      }
      return (R) new TypeRecord(list);
    }
    public R visit(org.syntax.stella.Absyn.ConsList p, A arg)
    { /* Cons operator: head :: tail */
      Context ctx = (Context) arg;
      if (ctx.expected != null && !(ctx.expected instanceof TypeList)) {
        throw new TypeError(ERR_UNEXPECTED_LIST + ": expected " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeList el) {
        Type headTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(el.type_));
        ensureEqual("cons head", el.type_, headTy);
        Type tailTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(new TypeList(el.type_)));
        ensureEqual("cons tail", new TypeList(el.type_), tailTy);
        return (R) new TypeList(el.type_);
      }

      //нет ожидаемого
      Type tailTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), arg);
      if (!(tailTy instanceof TypeList)) {
        throw new TypeError(ERR_UNEXP_TYPE_FOR("cons tail", new TypeList(new TypeNat()), tailTy));
      }
      Type elem = ((TypeList) tailTy).type_;
      Type headTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(elem));
      ensureEqual("cons head", elem, headTy);
      return (R) new TypeList(elem);
    }
    public R visit(org.syntax.stella.Absyn.Head p, A arg)
    { /* List::head */
      Context ctx = (Context) arg;
      Type lt = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
      TypeList tl = expectListType(lt, "List::head");
      return (R) tl.type_;
    }
    public R visit(org.syntax.stella.Absyn.IsEmpty p, A arg)
    { /* List::isempty */
      Context ctx = (Context) arg;
      Type lt = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
      expectListType(lt, "List::isempty");
      return (R) new TypeBool();
    }
    public R visit(org.syntax.stella.Absyn.Tail p, A arg)
    { /* List::tail */
      Context ctx = (Context) arg;
      Type lt = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(null));
      TypeList tl = expectListType(lt, "List::tail");
      return (R) new TypeList(tl.type_);
    }
    public R visit(org.syntax.stella.Absyn.Panic p, A arg)
    { /* Panic: type is the expected type, otherwise ambiguous */
      Context ctx = (Context) arg;
      if (ctx.expected == null) {
        throw new TypeError(ERROR_AMBIGUOUS_PANIC_TYPE + ": panic has no expected type");
      }
      return (R) ctx.expected;
    }
    public R visit(org.syntax.stella.Absyn.Throw p, A arg)
    { /* Throw: expression must have declared exception type; result is expected type */
      Context ctx = (Context) arg;
      if (ctx.exceptionType == null) {
        throw new TypeError(ERROR_EXCEPTION_TYPE_NOT_DECLARED + ": throw without declared exception type");
      }
      Type exTy = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(ctx.exceptionType));
      ensureEqual("throw value", ctx.exceptionType, exTy);
      if (ctx.expected == null) {
        throw new TypeError(ERROR_AMBIGUOUS_THROW_TYPE + ": cannot infer type of throw-expression");
      }
      return (R) ctx.expected;
    }
    public R visit(org.syntax.stella.Absyn.TryCatch p, A arg)
    { /* Try-catch: both branches must have the same type */
      Context ctx = (Context) arg;
      if (ctx.exceptionType == null) {
        throw new TypeError(ERROR_EXCEPTION_TYPE_NOT_DECLARED + ": try-catch without declared exception type");
      }
      Type tryTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), arg);
      Map<String, Type> binds = checkPatternAndBindings(p.pattern_, ctx.exceptionType);
      Context catchCtx = ctx.copy();
      for (Map.Entry<String, Type> e : binds.entrySet())
        catchCtx.bind(e.getKey(), e.getValue());
      Type expectedCatch = (ctx.expected != null ? ctx.expected : tryTy);
      Type catchTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), (A) catchCtx.withExpected(expectedCatch));
      if (ctx.expected != null) {
        ensureEqual("try-catch", ctx.expected, tryTy);
        ensureEqual("try-catch", ctx.expected, catchTy);
        return (R) ctx.expected;
      }
      ensureEqual("try-catch", tryTy, catchTy);
      return (R) tryTy;
    }
    public R visit(org.syntax.stella.Absyn.TryWith p, A arg)
    { /* Try-with: both expressions must have the same type */
      Context ctx = (Context) arg;
      Type tryTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), arg);
      Type expectedWith = (ctx.expected != null ? ctx.expected : tryTy);
      Type withTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(expectedWith));
      if (ctx.expected != null) {
        ensureEqual("try-with", ctx.expected, tryTy);
        ensureEqual("try-with", ctx.expected, withTy);
        return (R) ctx.expected;
      }
      ensureEqual("try-with", tryTy, withTy);
      return (R) tryTy;
    }
    public R visit(org.syntax.stella.Absyn.TryCastAs p, A arg)
    { /* Code for TryCastAs goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      p.expr_3.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Inl p, A arg)
    { /* Sum type injection: inl */
      Context ctx = (Context) arg;
      if (ctx.expected != null && !(ctx.expected instanceof TypeSum)) {
        throw new TypeError(ERR_UNEXPECTED_INJECTION + ": expected1 " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeSum ts) {
        Type leftTy = ts.type_1;
        Type et = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(leftTy));
        ensureEqual("inl injection", leftTy, et);
        return (R) ts;
      }
      p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      throw new TypeError(ERR_AMBIGUOUS_SUM_TYPE + ": cannot infer other side of sum for inl");
    }
    public R visit(org.syntax.stella.Absyn.Inr p, A arg)
    { /* Sum type injection: inr */
      Context ctx = (Context) arg;
      if (ctx.expected != null && !(ctx.expected instanceof TypeSum)) {
        throw new TypeError(ERR_UNEXPECTED_INJECTION + ": expected2 " + PrettyPrinter.print(ctx.expected));
      }
      if (ctx.expected instanceof TypeSum ts) {
        Type rightTy = ts.type_2;
        Type et = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(rightTy));
        ensureEqual("inr injection", rightTy, et);
        return (R) ts;
      }
      p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      throw new TypeError(ERR_AMBIGUOUS_SUM_TYPE + ": cannot infer other side of sum for inr");
    }
    public R visit(org.syntax.stella.Absyn.Succ p, A arg)
    { /* Code for Succ goes here */
      Context ctx = (Context) arg;
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      ensureEqual("succ argument", new TypeNat(), t);
      return (R) new TypeNat();
    }
    public R visit(org.syntax.stella.Absyn.LogicNot p, A arg)
    { /* Code for LogicNot goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Pred p, A arg)
    { /* Code for Pred goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.IsZero p, A arg)
    { /* Code for IsZero goes here */
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      ensureEqual("Nat::iszero argument", new TypeNat(), t);
      return (R) new TypeBool();
    }
    public R visit(org.syntax.stella.Absyn.Fix p, A arg)
    { /* Fixpoint combinator: (fn(T)->T) -> T */
      Type t = (Type) p.expr_.accept(new ExprVisitor<Type,A>(), arg);
      TypeFun tf = expectFunType(t, "fix");
      if (tf.listtype_.size() != 1) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": fix expects unary function, got " + PrettyPrinter.print(t));
      }
      Type a = tf.listtype_.get(0);
      Type r = tf.type_;
      ensureEqual("fix function type", a, r);
      return (R) a;
    }
    public R visit(org.syntax.stella.Absyn.NatRec p, A arg)
    { /* Code for NatRec goes here */
      Type nTy = (Type) p.expr_1.accept(new ExprVisitor<Type,A>(), arg);
      ensureEqual("Nat::rec n", new TypeNat(), nTy);
      Type zTy = (Type) p.expr_2.accept(new ExprVisitor<Type,A>(), arg);
      Context ctx = (Context) arg;
      Type expectedStepTy = mkFun(new TypeNat(), mkFun(zTy, zTy));
      TypeFun s1 = expectFunType((Type) p.expr_3.accept(new ExprVisitor<Type,A>(), (A) ctx.withExpected(expectedStepTy)), "Nat::rec s");
      if (s1.listtype_.size() != 1 || !(s1.listtype_.get(0) instanceof TypeNat)) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": Nat::rec step expects parameter Nat, got " + PrettyPrinter.print(s1));
      }
      TypeFun s2 = expectFunType(s1.type_, "Nat::rec s result");
      if (s2.listtype_.size() != 1) {
        throw new TypeError(ERR_UNEXP_TYPE_EXPR + ": Nat::rec step must return unary function, got " + PrettyPrinter.print(s2));
      }
      Type stepArg = s2.listtype_.get(0);
      ensureEqual("Nat::rec step accumulator", zTy, stepArg);
      ensureEqual("Nat::rec step result", zTy, s2.type_);
      return (R) zTy;
    }
    public R visit(org.syntax.stella.Absyn.Fold p, A arg)
    { /* Code for Fold goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.Unfold p, A arg)
    { /* Code for Unfold goes here */
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(org.syntax.stella.Absyn.ConstTrue p, A arg)
    { /* Code for ConstTrue goes here */
      return (R) new TypeBool();
    }
    public R visit(org.syntax.stella.Absyn.ConstFalse p, A arg)
    { /* Code for ConstFalse goes here */
      return (R) new TypeBool();
    }
    public R visit(org.syntax.stella.Absyn.ConstUnit p, A arg)
    { /* Code for ConstUnit goes here */
      return (R) new TypeUnit();
    }
    public R visit(org.syntax.stella.Absyn.ConstInt p, A arg)
    { /* Code for ConstInt goes here */
      return (R) new TypeNat();
    }
    public R visit(org.syntax.stella.Absyn.ConstMemory p, A arg)
    { /* Memory address literal: must have expected reference type */
      Context ctx = (Context) arg;
      if (ctx.expected == null) {
        throw new TypeError(ERROR_AMBIGUOUS_REFERENCE_TYPE + ": bare memory address without expected reference type");
      }
      if (!(ctx.expected instanceof TypeRef)) {
        throw new TypeError(ERROR_UNEXPECTED_MEMORY_ADDRESS + ": expected " + PrettyPrinter.print(ctx.expected));
      }
      return (R) ctx.expected;
    }
    public R visit(org.syntax.stella.Absyn.Var p, A arg)
    { /* Code for Var goes here */
      Context ctx = (Context) arg;
      return (R) ctx.lookup(p.stellaident_);
    }
    
  }
  public class PatternBindingVisitor<R,A> implements org.syntax.stella.Absyn.PatternBinding.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.APatternBinding p, A arg)
    { /* Code for APatternBinding goes here */
      p.pattern_.accept(new PatternVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
  }
  public class VariantFieldTypeVisitor<R,A> implements org.syntax.stella.Absyn.VariantFieldType.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.AVariantFieldType p, A arg)
    { /* Code for AVariantFieldType goes here */
      //p.stellaident_;
      p.optionaltyping_.accept(new OptionalTypingVisitor<R,A>(), arg);
      return null;
    }
  }
  public class RecordFieldTypeVisitor<R,A> implements org.syntax.stella.Absyn.RecordFieldType.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.ARecordFieldType p, A arg)
    { /* Code for ARecordFieldType goes here */
      //p.stellaident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class TypingVisitor<R,A> implements org.syntax.stella.Absyn.Typing.Visitor<R,A>
  {
    public R visit(org.syntax.stella.Absyn.ATyping p, A arg)
    { /* Code for ATyping goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
}
